# Base configs
baseurl: "https://www.ashu-photo.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-56989356-1"

# UI configs
title: "Photography by A Shu"
subtitle: ""
author: "A Shu"
bio: "If you can get everything from your dream, why would you wake up?"
publicise: ""
web_design: ""
social_urls:
  instagram: "https://www.instagram.com/ashu.photo"
  
theme: jekyll-theme-cayman
